[2023-12-24T14:03:44.233+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:03:44.234+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:03:44.237+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:03:44.237+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:03:44.246+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:03:44.245+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:03:44.247+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:03:44.269+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.039 seconds
[2023-12-24T14:05:44.190+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:05:44.211+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:05:44.217+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:05:44.216+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:05:44.264+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:05:44.249+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:05:44.265+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:05:44.332+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.150 seconds
[2023-12-24T14:06:33.740+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:06:33.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:06:33.747+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:06:33.747+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:06:33.763+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:06:33.761+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:06:33.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:06:33.796+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.065 seconds
[2023-12-24T14:07:03.954+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:07:03.957+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:07:03.978+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:07:03.978+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:07:04.027+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:07:04.008+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:07:04.030+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:07:04.090+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.144 seconds
[2023-12-24T14:07:34.190+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:07:34.195+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:07:34.213+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:07:34.213+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:07:34.244+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:07:34.241+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:07:34.245+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:07:34.308+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.128 seconds
[2023-12-24T14:08:05.016+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:08:05.018+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:08:05.023+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:08:05.022+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:08:05.032+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:08:05.030+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:08:05.034+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:08:05.069+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.060 seconds
[2023-12-24T14:08:35.245+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:08:35.246+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:08:35.251+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:08:35.251+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:08:35.259+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:08:35.258+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:08:35.260+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:08:35.289+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.050 seconds
[2023-12-24T14:09:06.026+0000] {processor.py:161} INFO - Started process (PID=331) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:09:06.028+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:09:06.033+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:09:06.032+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:09:06.042+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:09:06.040+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:09:06.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:09:06.075+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.057 seconds
[2023-12-24T14:09:36.137+0000] {processor.py:161} INFO - Started process (PID=389) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:09:36.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:09:36.144+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:09:36.144+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:09:36.154+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:09:36.151+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:09:36.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:09:36.197+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.068 seconds
[2023-12-24T14:10:06.474+0000] {processor.py:161} INFO - Started process (PID=449) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:10:06.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:10:06.481+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:10:06.480+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:10:06.490+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:10:06.488+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:10:06.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:10:06.529+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.063 seconds
[2023-12-24T14:10:37.102+0000] {processor.py:161} INFO - Started process (PID=507) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:10:37.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:10:37.109+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:10:37.108+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:10:37.121+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:10:37.119+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:10:37.122+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:10:37.171+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.075 seconds
[2023-12-24T14:11:07.453+0000] {processor.py:161} INFO - Started process (PID=566) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:11:07.454+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:11:07.461+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:11:07.461+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:11:07.470+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:11:07.468+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:11:07.471+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:11:07.519+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.073 seconds
[2023-12-24T14:11:38.345+0000] {processor.py:161} INFO - Started process (PID=626) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:11:38.347+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:11:38.353+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:11:38.353+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:11:38.369+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:11:38.367+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:11:38.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:11:38.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.119 seconds
[2023-12-24T14:12:08.960+0000] {processor.py:161} INFO - Started process (PID=684) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:12:08.966+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:12:08.973+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:12:08.973+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:12:08.982+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:12:08.980+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:12:08.983+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:12:09.021+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.069 seconds
[2023-12-24T14:12:39.673+0000] {processor.py:161} INFO - Started process (PID=743) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:12:39.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:12:39.687+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:12:39.686+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:12:39.702+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:12:39.699+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:12:39.704+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:12:39.752+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.087 seconds
[2023-12-24T14:13:10.425+0000] {processor.py:161} INFO - Started process (PID=802) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:13:10.427+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:13:10.433+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:13:10.432+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:13:10.442+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:13:10.440+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:13:10.443+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:13:10.482+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.065 seconds
[2023-12-24T14:13:40.935+0000] {processor.py:161} INFO - Started process (PID=861) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:13:40.936+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:13:40.941+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:13:40.941+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:13:40.950+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:13:40.948+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:13:40.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:13:40.982+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.054 seconds
[2023-12-24T14:14:11.016+0000] {processor.py:161} INFO - Started process (PID=919) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:14:11.018+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:14:11.023+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:14:11.022+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:14:11.031+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:14:11.029+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:14:11.032+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:14:11.061+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.051 seconds
[2023-12-24T14:14:41.220+0000] {processor.py:161} INFO - Started process (PID=978) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:14:41.222+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:14:41.226+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:14:41.226+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:14:41.234+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:14:41.233+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:14:41.235+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:14:41.263+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.048 seconds
[2023-12-24T14:15:11.356+0000] {processor.py:161} INFO - Started process (PID=1037) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:15:11.357+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:15:11.362+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:15:11.362+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:15:11.370+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:15:11.369+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:15:11.371+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:15:11.401+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.052 seconds
[2023-12-24T14:15:41.967+0000] {processor.py:161} INFO - Started process (PID=1097) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:15:41.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:15:41.974+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:15:41.973+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:15:41.985+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:15:41.983+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:15:41.986+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:15:42.026+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.068 seconds
[2023-12-24T14:16:12.786+0000] {processor.py:161} INFO - Started process (PID=1156) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:16:12.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:16:12.793+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:16:12.792+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:16:12.810+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:16:12.808+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:16:12.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:16:12.846+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.068 seconds
[2023-12-24T14:18:36.680+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:18:36.686+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:18:36.692+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:18:36.691+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:18:36.749+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:18:36.726+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:18:36.750+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:18:36.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.172 seconds
[2023-12-24T14:19:06.988+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:19:06.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:19:06.995+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:19:06.995+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:19:07.006+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:19:07.003+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:19:07.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:19:07.078+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.097 seconds
[2023-12-24T14:19:37.503+0000] {processor.py:161} INFO - Started process (PID=161) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:19:37.505+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:19:37.512+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:19:37.510+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:19:37.523+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:19:37.521+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:19:37.525+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:19:37.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.072 seconds
[2023-12-24T14:20:07.722+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:20:07.725+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:20:07.732+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:20:07.731+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:20:07.751+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:20:07.748+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:20:07.753+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:20:07.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.094 seconds
[2023-12-24T14:20:38.007+0000] {processor.py:161} INFO - Started process (PID=279) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:20:38.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:20:38.015+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:20:38.014+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:20:38.028+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:20:38.025+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:20:38.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:20:38.068+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.066 seconds
[2023-12-24T14:21:08.393+0000] {processor.py:161} INFO - Started process (PID=337) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:21:08.396+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:21:08.402+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:21:08.401+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:21:08.414+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:21:08.412+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:21:08.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:21:08.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.072 seconds
[2023-12-24T14:21:39.014+0000] {processor.py:161} INFO - Started process (PID=396) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:21:39.016+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:21:39.021+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:21:39.020+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:21:39.032+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:21:39.029+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:21:39.033+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:21:39.068+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.059 seconds
[2023-12-24T14:22:09.550+0000] {processor.py:161} INFO - Started process (PID=454) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:22:09.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:22:09.558+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:22:09.557+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:22:09.570+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:22:09.567+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:22:09.571+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:22:09.601+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.060 seconds
[2023-12-24T14:22:39.963+0000] {processor.py:161} INFO - Started process (PID=512) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:22:39.965+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:22:39.970+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:22:39.969+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:22:39.977+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:22:39.976+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:22:39.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:22:40.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.052 seconds
[2023-12-24T14:23:10.235+0000] {processor.py:161} INFO - Started process (PID=570) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:23:10.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:23:10.243+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:23:10.242+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:23:10.253+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:23:10.250+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:23:10.254+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:23:10.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.064 seconds
[2023-12-24T14:23:40.345+0000] {processor.py:161} INFO - Started process (PID=628) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:23:40.346+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:23:40.353+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:23:40.352+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:23:40.364+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:23:40.362+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:23:40.365+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:23:40.394+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.055 seconds
[2023-12-24T14:24:10.516+0000] {processor.py:161} INFO - Started process (PID=686) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:24:10.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:24:10.523+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:24:10.522+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:24:10.532+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:24:10.530+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:24:10.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:24:10.572+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.061 seconds
[2023-12-24T14:24:40.910+0000] {processor.py:161} INFO - Started process (PID=744) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:24:40.911+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:24:40.917+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:24:40.916+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:24:40.928+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:24:40.926+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:24:40.929+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:24:40.965+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.062 seconds
[2023-12-24T14:25:11.181+0000] {processor.py:161} INFO - Started process (PID=802) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:25:11.189+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:25:11.205+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:25:11.204+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:25:11.226+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:25:11.224+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:25:11.232+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:25:11.307+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.135 seconds
[2023-12-24T14:25:41.414+0000] {processor.py:161} INFO - Started process (PID=860) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:25:41.415+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:25:41.420+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:25:41.419+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:25:41.427+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:25:41.426+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:25:41.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:25:41.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.045 seconds
[2023-12-24T14:26:11.681+0000] {processor.py:161} INFO - Started process (PID=918) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:26:11.683+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:26:11.689+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:26:11.689+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:26:11.699+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:26:11.697+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:26:11.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:26:11.733+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.058 seconds
[2023-12-24T14:26:41.879+0000] {processor.py:161} INFO - Started process (PID=976) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:26:41.881+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:26:41.885+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:26:41.885+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:26:41.894+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:26:41.892+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:26:41.895+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:26:41.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.062 seconds
[2023-12-24T14:27:12.651+0000] {processor.py:161} INFO - Started process (PID=1034) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:27:12.657+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:27:12.668+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:27:12.667+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:27:12.686+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:27:12.683+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:27:12.718+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:27:12.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.138 seconds
[2023-12-24T14:27:43.231+0000] {processor.py:161} INFO - Started process (PID=1092) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:27:43.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:27:43.237+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:27:43.236+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:27:43.245+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:27:43.243+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:27:43.246+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:27:43.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.056 seconds
[2023-12-24T14:28:13.392+0000] {processor.py:161} INFO - Started process (PID=1150) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:28:13.393+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:28:13.398+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:28:13.397+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:28:13.406+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:28:13.404+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:28:13.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:28:13.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.053 seconds
[2023-12-24T14:28:43.636+0000] {processor.py:161} INFO - Started process (PID=1208) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:28:43.638+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:28:43.643+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:28:43.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:28:43.652+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:28:43.650+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:28:43.654+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:28:43.696+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.065 seconds
[2023-12-24T14:29:14.030+0000] {processor.py:161} INFO - Started process (PID=1264) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:29:14.032+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:29:14.038+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:29:14.037+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:29:14.050+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:29:14.048+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:29:14.051+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:29:14.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.082 seconds
[2023-12-24T14:29:44.768+0000] {processor.py:161} INFO - Started process (PID=1321) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:29:44.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:29:44.778+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:29:44.777+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:29:44.790+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:29:44.788+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:29:44.791+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:29:44.831+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.071 seconds
[2023-12-24T14:30:15.006+0000] {processor.py:161} INFO - Started process (PID=1379) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:30:15.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:30:15.015+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:30:15.014+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:30:15.026+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:30:15.023+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:30:15.027+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:30:15.072+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.073 seconds
[2023-12-24T14:30:45.688+0000] {processor.py:161} INFO - Started process (PID=1437) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:30:45.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:30:45.694+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:30:45.693+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:30:45.702+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:30:45.701+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:30:45.703+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:30:45.732+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.053 seconds
[2023-12-24T14:31:16.325+0000] {processor.py:161} INFO - Started process (PID=1495) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:31:16.327+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:31:16.331+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:31:16.331+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:31:16.340+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:31:16.338+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:31:16.340+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:31:16.374+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.055 seconds
[2023-12-24T14:33:19.096+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:33:19.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:33:19.110+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:33:19.109+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:33:19.135+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:33:19.133+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:33:19.138+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:33:19.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.135 seconds
[2023-12-24T14:33:49.359+0000] {processor.py:161} INFO - Started process (PID=99) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:33:49.360+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:33:49.365+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:33:49.364+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:33:49.373+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:33:49.371+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:33:49.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:33:49.412+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.059 seconds
[2023-12-24T14:34:19.489+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:34:19.491+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:34:19.496+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:34:19.496+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:34:19.506+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:34:19.504+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:34:19.507+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:34:19.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.061 seconds
[2023-12-24T14:34:49.830+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:34:49.832+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:34:49.840+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:34:49.839+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:34:49.850+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:34:49.847+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:34:49.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:34:49.885+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.062 seconds
[2023-12-24T14:35:20.189+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:35:20.192+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:35:20.200+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:35:20.199+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:35:20.213+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:35:20.211+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:35:20.214+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:35:20.257+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.075 seconds
[2023-12-24T14:35:50.736+0000] {processor.py:161} INFO - Started process (PID=332) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:35:50.738+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:35:50.743+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:35:50.742+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:35:50.752+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:35:50.750+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:35:50.753+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:35:50.789+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.060 seconds
[2023-12-24T14:36:21.481+0000] {processor.py:161} INFO - Started process (PID=390) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:36:21.482+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:36:21.487+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:36:21.486+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:36:21.496+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:36:21.494+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:36:21.497+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:36:21.532+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.057 seconds
[2023-12-24T14:36:51.829+0000] {processor.py:161} INFO - Started process (PID=448) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:36:51.831+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:36:51.835+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:36:51.834+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:36:51.844+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:36:51.842+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:36:51.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:36:51.877+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.053 seconds
[2023-12-24T14:37:22.057+0000] {processor.py:161} INFO - Started process (PID=506) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:37:22.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:37:22.063+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:37:22.063+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:37:22.073+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:37:22.071+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:37:22.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:37:22.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.055 seconds
[2023-12-24T14:37:52.828+0000] {processor.py:161} INFO - Started process (PID=564) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:37:52.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:37:52.836+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:37:52.835+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:37:52.851+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:37:52.848+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:37:52.852+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:37:52.888+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.070 seconds
[2023-12-24T14:38:23.569+0000] {processor.py:161} INFO - Started process (PID=623) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:38:23.573+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:38:23.581+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:38:23.580+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:38:23.597+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:38:23.595+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:38:23.599+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:38:23.645+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.087 seconds
[2023-12-24T14:38:53.725+0000] {processor.py:161} INFO - Started process (PID=682) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:38:53.727+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:38:53.731+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:38:53.731+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:38:53.741+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:38:53.740+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:38:53.742+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:38:53.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.056 seconds
[2023-12-24T14:39:23.970+0000] {processor.py:161} INFO - Started process (PID=741) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:39:23.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:39:23.977+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:39:23.976+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:39:23.985+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:39:23.983+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:39:23.985+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:39:24.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.055 seconds
[2023-12-24T14:39:54.135+0000] {processor.py:161} INFO - Started process (PID=800) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:39:54.136+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:39:54.142+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:39:54.141+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:39:54.151+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:39:54.149+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:39:54.151+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:39:54.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.054 seconds
[2023-12-24T14:40:24.417+0000] {processor.py:161} INFO - Started process (PID=860) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:40:24.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:40:24.426+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:40:24.425+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:40:24.437+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:40:24.435+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:40:24.438+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:40:24.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.066 seconds
[2023-12-24T14:40:54.658+0000] {processor.py:161} INFO - Started process (PID=919) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:40:54.660+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:40:54.667+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:40:54.666+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:40:54.680+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:40:54.676+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:40:54.682+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:40:54.724+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.076 seconds
[2023-12-24T14:41:25.411+0000] {processor.py:161} INFO - Started process (PID=978) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:41:25.412+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:41:25.418+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:41:25.418+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:41:25.427+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:41:25.426+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:41:25.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:41:25.469+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.065 seconds
[2023-12-24T14:41:55.806+0000] {processor.py:161} INFO - Started process (PID=1037) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:41:55.809+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:41:55.817+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:41:55.816+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:41:55.831+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:41:55.829+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:41:55.833+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:41:55.910+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.111 seconds
[2023-12-24T14:42:26.386+0000] {processor.py:161} INFO - Started process (PID=1096) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:42:26.387+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:42:26.393+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:42:26.392+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:42:26.402+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:42:26.400+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:42:26.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:42:26.436+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.057 seconds
[2023-12-24T14:42:57.000+0000] {processor.py:161} INFO - Started process (PID=1155) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:42:57.002+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:42:57.007+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:42:57.006+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:42:57.016+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:42:57.014+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:42:57.017+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:42:57.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.057 seconds
[2023-12-24T14:43:27.092+0000] {processor.py:161} INFO - Started process (PID=1214) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:43:27.093+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:43:27.099+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:43:27.098+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:43:27.111+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:43:27.108+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:43:27.112+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:43:27.147+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.063 seconds
[2023-12-24T14:43:57.384+0000] {processor.py:161} INFO - Started process (PID=1273) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:43:57.386+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:43:57.397+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:43:57.395+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:43:57.412+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:43:57.408+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:43:57.414+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:43:57.460+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.082 seconds
[2023-12-24T14:44:27.890+0000] {processor.py:161} INFO - Started process (PID=1332) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:44:27.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:44:27.896+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:44:27.895+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:44:27.904+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:44:27.902+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:44:27.905+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:44:27.940+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.056 seconds
[2023-12-24T14:44:58.450+0000] {processor.py:161} INFO - Started process (PID=1391) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:44:58.455+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:44:58.464+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:44:58.463+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:44:58.505+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:44:58.500+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:44:58.510+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:44:58.613+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.173 seconds
[2023-12-24T14:45:28.711+0000] {processor.py:161} INFO - Started process (PID=1450) to work on /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:45:28.724+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_dbt.py for tasks to queue
[2023-12-24T14:45:28.738+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:45:28.734+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:45:28.781+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:45:28.775+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_dbt.py", line 7, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2023-12-24T14:45:28.784+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_dbt.py
[2023-12-24T14:45:28.905+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_dbt.py took 0.218 seconds
